#!/bin/csh

\rm -rf ~/matlab/pack_up/eigtoollib/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/private/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/numcomp/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/numcomp/pseudo_abscissa/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/numcomp/pseudo_abscissa/private/.svn
irm -rf ~/matlab/pack_up/eigtoollib/numcomp/pseudo_radius/private/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/images/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/buttons/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/images/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/options/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/panes/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/html/eigtool/documentation/proj_tutorial/.svn
\rm -rf ~/matlab/pack_up/eigtoollib/NEW_MEX
\rm -rf ~/matlab/pack_up/eigtoollib/OLD_MEX
\rm -rf ~/matlab/pack_up/eigtoollib/NOTES
\rm ~/matlab/pack_up/eigtoollib/private/psacore.mex*
cd ~/matlab/pack_up
zip -r eigtoollib.zip eigtoollib
tar cf eigtoollib.tar eigtoollib
gzip eigtoollib.tar


