#!/bin/sh
 for args
    do
      verstring="% Version 2.1 (`date`)"
      awk '{if ($0~/% Version /) { print "'"$verstring"'"} 
            else {if ($0~/% Copyright/) 
                 { print "% Copyright 2002 - 2009 by Tom Wright; maintained by Mark Embree (embree@rice.edu)"} 
            else {print $0}}}'  $args > $$.tmp
      mv -f $$.tmp $args
    done
